##############################
#  _
# | |_ _ __ ___  _   ___  __
# | __| '_ ` _ \| | | \ \/ /
# | |_| | | | | | |_| |>  <
#  \__|_| |_| |_|\__,_/_/\_\
#
#############################

# Set TERM so iTerm2 can read it and display colors properly
# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#italics-show-up-as-reverse-video-whole-screen-reverse-video-isnt-working-or-my-term-variable-is-not-what-i-wish
set -g default-terminal "xterm-256color"
# set -ga terminal-overrides ",xterm-256color:Tc"

# Use tmux window titles in native tab and window titles
# https://gitlab.com/gnachman/iterm2/-/wikis/tmux-Integration-Best-Practices#i-want-to-see-tmux-window-titles-as-tabwindow-titles-in-iterm2
set-option -g set-titles on
set-option -g set-titles-string '#T'
