" tpope defaults - redundant with tpope/vim-sensible???
" source $VIMRUNTIME/defaults.vim

" Some basics:
if &compatible
  " `:set nocp` has many side effects. Therefore this should be done
  " only when 'compatible' is set.
  set nocompatible
endif

runtime! plugin/sensible.vim

" Configure ALE linter plugin to work with coc.nvim
" let g:ale_disable_lsp = 1

" Use MinPac plugin manager
" packadd minpac
if exists('g:loaded_minpac')
  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  " Additional plugins here
  call minpac#add('tpope/vim-sensible')
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-endwise')
  call minpac#add('tpope/vim-eunuch')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-tbone')
  call minpac#add('tpope/vim-rails')
  call minpac#add('tpope/vim-rake')
  call minpac#add('tpope/vim-bundler')
  call minpac#add('tpope/vim-dadbod')
  call minpac#add('tpope/vim-dispatch')
  call minpac#add('tpope/vim-unimpaired')
  call minpac#add('tpope/vim-abolish')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-projectionist')
  call minpac#add('jiangmiao/auto-pairs')
  call minpac#add('gruvbox-community/gruvbox')
  call minpac#add('nathanaelkane/vim-indent-guides')
  call minpac#add('mattn/emmet-vim')

  " Finders
  " call minpac#add('mileszs/ack.vim')
  call minpac#add('ctrlpvim/ctrlp.vim')

  " IDE
  call minpac#add('neoclide/coc.nvim')
  " call minpac#add('dense-analysis/ale')
  call minpac#add('puremourning/vimspector') " Full-featured debugger inside Vim
  call minpac#add('c-brenn/fuzzy-projectionist.vim')
  call minpac#add('vim-test/vim-test')

  " Language-specific
  call minpac#add('sheerun/vim-polyglot') " collection of all language packs

  " Elixir
  call minpac#add('amiralies/coc-elixir')
  call minpac#add('slashmili/alchemist.vim')
  call minpac#add('dkuku/vim-projectionist-elixir')

  call minpac#add('vim-airline/vim-airline')
  call minpac#add('vim-airline/vim-airline-themes')

  " JavaScript/TypeScript
  call minpac#add('prettier/vim-prettier')
  call minpac#add('yuezk/vim-js')
  call minpac#add('maxmellon/vim-jsx-pretty')

  " CSS
  call minpac#add('hail2u/vim-css3-syntax')
  " call minpac#add('iamcco/coc-tailwindcss')

  " Ruby
  call minpac#add('sunaku/vim-ruby-minitest')
  call minpac#add('ecomba/vim-ruby-refactoring')

  " Markdown
  " call minpac#add('instant-markdown/vim-instant-markdown')
endif

let mapleader = " "

if has('autocmd')
  filetype plugin indent on
endif

if has('syntax') && !exists('g:syntax_on')
  syntax enable
endif

" Environment variables
let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"
let $FTP="$HOME/.vim/after/ftplugin"

" Basic options
set encoding=utf-8
filetype on
set number relativenumber
set noerrorbells
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set smartcase
set nowrap
set backspace=indent,eol,start
set ruler
set matchpairs+=<:>
set fixendofline
set showcmd
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set foldmethod=syntax
set foldenable
set foldlevel=1 " Don't fold the top-level class/module in a file
set textwidth=80
nnoremap Q gq
" Indent the whole file
nnoremap g<C-G> gg=G<C-O><C-O>

" Use <C-L> to clear the highlighting of :set hlsearch.
if maparg('<C-L>', 'n') ==# ''
  nnoremap <silent> <C-L> :nohlsearch<C-R>=has('diff')?'<Bar>diffupdate':''<CR><CR><C-L>
endif

" FINDING FILES:
" Usage:
" - Hit tab to :find by partial match
" - Use * to make it fuzzy

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**
set path-=vendor/bundle/
set tagcase=followscs
set wildmenu
set wildchar=<Tab>
set wildmode=list:longest " default: full
set complete+=kspell
set completeopt=menuone,longest

" https://stackoverflow.com/a/23015387/12344822
if exists("g:ctrlp_user_command")
  unlet g:ctrlp_user_command
endif
" Ignore irrelevant and vendor directories
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*/node_modules/*,*/_site/*,*/vendor/*,*/_build/*,*/deps/*
" Ignore static asset files
set wildignore+=*/*.png,*/*.jpg,*/*.jpeg
set infercase
" Autocomplete remappings (saves a keystroke (^X))
inoremap ^L ^X^L

" TAG JUMPING
" Create the 'tags' file
" command! MakeTags  !ctags -R
" command! MakeTagsExclude !ctags -R --exclude=@.ctagsignore .
" Generate tags based on git
command! MakeTags !git ls-files | ctags -L -

" Disables automatic commenting on newline:
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

" Splits open at the bottom and right
set splitbelow splitright

" Shortcutting split navigation, saving a keypress:
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" Ensure files are read as what I want:
augroup FiletypeGroup
  autocmd!
  au!
  let g:vimwiki_ext2syntax = {'.Rmd': 'markdown', '.rmd': 'markdown','.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
  autocmd BufRead,BufNewFile /tmp/calcurse*,~/.calcurse/notes/* set filetype=markdown
  autocmd BufRead,BufNewFile *.ms,*.me,*.mom,*.man set filetype=groff
  autocmd BufRead,BufNewFile *.tex set filetype=tex
  autocmd BufRead,BufNewFile *.erb set filetype=html
  au BufNewFile,BufRead *.jsx set filetype=javascript,jsx
augroup END

" When shortcut files are updated, renew bash and ranger configs with new material:
" autocmd BufWritePost ~/.bm* !shortcuts

" Source .vimrc
command! Ref source $RC

" Move lines up and down
nnoremap <Leader>j :m +1<CR>
vnoremap <Leader>j :m +1<CR>
nnoremap <Leader>k :m -2<CR>
vnoremap <Leader>k :m -2<CR>

" Surround
let g:surround_45 = "<% \r %>"
let g:surround_61 = "<%= \r %>"

" NERDTree Plugin:
" Toggle NERDTree using <Leader>f
nnoremap <Leader>f :NERDTreeToggle<Enter>

" CTRL-P Plugin:
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_mruf_relative = 1
" Use <F2> to toggle whether MRU limits results to files within the current
" working directory
let g:ctrlp_prompt_mappings = { 'ToggleMRURelative()': ['<F2>'] }
let g:ctrlp_by_filename = 1
let g:ctrlp_working_path_mode = 'rwa'

" Built-in Terminal Display:
" (vim 8.0+)
if exists('+termguicolors')
  set termguicolors
  let &t_ZH="\e[3m"
  let &t_ZR="\e[23m"
endif
set termwinsize="20x0"

" Colors:
colorscheme gruvbox
let g:gruvbox_italic='1'
let g:gruvbox_contrast_dark = 'hard'
set background=dark
set t_Co=256
let g:gruvbox_invert_selection='1'
highlight Comment cterm=italic gui=italic
highlight ColorColumn guibg=darkgray

" Airline Plugin:
let g:airline_theme='base16_gruvbox_dark_hard'
" Display ALE error information in Airline status bar
" https://github.com/dense-analysis/ale#5vii-how-can-i-show-errors-or-warnings-in-my-statusline
let g:airline#extensions#ale#enabled = 1

" ALE Plugin:
" Set when ALE runs the linter and fixer
let g:ale_fix_on_save = 1 " default 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 0
let g:ale_lint_on_enter = 0
" Move between errors with Ctrl+- and Ctrl+=
nmap <silent> <C--> <Plug>(ale_previous_wrap)
nmap <silent> <C-=> <Plug>(ale_next_wrap)
" Bind F8 to run ALE Fix
nmap <F8> <Plug>(ale_fix)

" Set internal encoding of vim, not needed on neovim, since coc.nvim using some
" unicode characters in the file autoload/float.vim
set encoding=utf-8

" TextEdit might fail if hidden is not set.
set hidden

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable
" delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn, otherwise it would shift the text each time
" diagnostics appear/become resolved.
if has("nvim-0.5.0") || has("patch-8.1.1564")
  " Recently vim can merge signcolumn and number column into one
  set signcolumn=number
else
  set signcolumn=yes
endif

" Use tab for trigger completion with characters ahead and navigate.
" NOTE: Use command ':verbose imap <tab>' to make sure tab is not mapped by
" other plugin before putting this into your config.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Use <c-space> to trigger completion.
if has('nvim')
  inoremap <silent><expr> <c-space> coc#refresh()
else
  inoremap <silent><expr> <c-@> coc#refresh()
endif

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  elseif (coc#rpc#ready())
    call CocActionAsync('doHover')
  else
    execute '!' . &keywordprg . " " . expand('<cword>')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Remap <C-f> and <C-b> for scroll float windows/popups.
if has('nvim-0.4.0') || has('patch-8.2.0750')
  nnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  nnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
  inoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(1)\<cr>" : "\<Right>"
  inoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? "\<c-r>=coc#float#scroll(0)\<cr>" : "\<Left>"
  vnoremap <silent><nowait><expr> <C-f> coc#float#has_scroll() ? coc#float#scroll(1) : "\<C-f>"
  vnoremap <silent><nowait><expr> <C-b> coc#float#has_scroll() ? coc#float#scroll(0) : "\<C-b>"
endif

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of language server.
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>

" Emmet
let g:user_emmet_leader_key = '<C-y>' " default <C-y>

" Ack.vim
nnoremap \ :Ack<SPACE>
if executable('ag')
  let g:ackprg = "ag --vimgrep"
endif
let g:ack_use_dispatch = 1
let g:ackhighlight = 1
let g:ackpreview = 1
let g:ack_use_cword_for_empty_search = 1

" Vim Instant Markdown
" https://github.com/instant-markdown/vim-instant-markdown#installation
" Uncomment to override defaults:
let g:instant_markdown_slow = 5
"let g:instant_markdown_autostart = 0
"let g:instant_markdown_open_to_the_world = 1
"let g:instant_markdown_allow_unsafe_content = 1
"let g:instant_markdown_allow_external_content = 0
"let g:instant_markdown_mathjax = 1
"let g:instant_markdown_mermaid = 1
"let g:instant_markdown_logfile = '/tmp/instant_markdown.log'
"let g:instant_markdown_autoscroll = 0
"let g:instant_markdown_port = 8888
"let g:instant_markdown_python = 1

" Vimspector Plugin
let g:vimspector_enable_mappings = "HUMAN" " Use default keybindings

" vim-test plugin
let test#strategy = "vimterminal"
nmap <silent> <leader>tn :TestNearest<CR>
nmap <silent> <leader>tf :TestFile<CR>
nmap <silent> <leader>ts :TestSuite<CR>
nmap <silent> <leader>tl :TestLast<CR>
nmap <silent> <leader>tg :TestVisit<CR>

" Minpac commands - use these to update packages
command! PackUpdate packadd minpac | source $MYVIMRC | call minpac#update('', {'do': 'call minpac#status()'})
command! PackClean  packadd minpac | source $MYVIMRC | call minpac#clean()
command! PackStatus packadd minpac | source $MYVIMRC | call minpac#status()

" Load all plugins right now. (optional)
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL

" REFERENCE
" Autocomplete:
" see |ins-completion|

" Example .vimrcs
" https://github.com/amix/vimrc
" https://github.com/LukeSmithxyz/voidrice/blob/master/.config/nvim/init.vim
" https://github.com/tpope/tpope/blob/master/.vimrc
