on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  nix-flake-check:
    strategy:
      matrix:
        system: ['macos-latest']
    runs-on: ${{ matrix.system }}
    defaults:
      run: 
        shell: bash

    steps:
      - uses: actions/checkout@v3

      # - name: Ensure Nix flake inputs are fresh
      #   # TODO: re-evaluate whether to allow failure
      #   continue-on-error: true
      #   uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix flake
        working-directory: '.config/darwin'
        run: nix flake check --keep-going --show-trace --print-build-logs
