on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  nix-flake-check:
    strategy:
      matrix:
        system: ['macos-latest']
    runs-on: ${{ matrix.system }}
    defaults:
      run: 
        shell: bash
    env:
      PATH_TO_DARWIN_FLAKE: '.config/darwin'

    steps:
      - uses: actions/checkout@v3

      # - name: Ensure Nix flake inputs are fresh
      #   # TODO: re-evaluate whether to allow failure
      #   continue-on-error: true
      #   uses: DeterminateSystems/flake-checker-action@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Cache Nix builds
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check Nix flake
        run: nix flake check --keep-going --show-trace --print-build-logs '${{ env.PATH_TO_DARWIN_FLAKE }}'

      - name: Configure local system using nix-darwin
        run: nix run "${{ env.PATH_TO_DARWIN_FLAKE }}#x86_64-darwin-no-linux-builder"
